#!/bin/bash
cat >dist/cjs/package.json <<!EOF
{
	"version": ${npm_package_version}
    "type": "commonjs"
}
!EOF

cat >dist/mjs/package.json <<!EOF
{
	"version": ${npm_package_version}
    "type": "module"
}
!EOF
